### ISSUE TITLE
first result hidden behind title bar

### ISSUE THREAD

**Issue by Sombreroz** [derjasper/TankenApp#10]
The first result is always hidden behind the title bar. I can pull the list down but as soon as I release the list snaps up again

**Comment by derjasper** [comment]
Thanks for your report!
On my 15.10 desktop this does not happen. I do not own an ubuntu phone yet and the emulator is currently broken, so I cannot test this. Perhaps, this is a bug in the UITK and will be fixed with OTA-9. Otherwise please be patient until I am able to reproduce this bug (when the emulator works again) or someone else submits a pull request.

**Comment by Sombreroz** [comment]
Thanks for your reply.
Let me know if I can help.

**Comment by derjasper** [comment]
Did anything change with the last Ubuntu update?

**Comment by Sombreroz** [comment]
Nothing has changed with OTA9.
BTW are you German?

**Comment by derjasper** [comment]
Yes, I am German ;)

I published 0.4.6. Can you install it and did it fix any of your issues?

**Comment by Sombreroz** [comment]
Hallo Jasper,

nein, keine Änderung. Ich bin übrigens auch in der Ubuntufun-Gruppe bei  
Telegram.
Utz ist mein Name.

Gruß
Utz

**Comment by derjasper** [comment]
This issue is fixed in the latest 0.4.7 release

**Comment by derjasper** [comment]
Ok, should finally be fixed  in 0.4.9

**Comment by Sombreroz** [comment]
Confirmed, it is fixed. Thank you!
