### ISSUE TITLE
Extend to italy

### ISSUE THREAD

**Issue by pharaone** [derjasper/TankenApp#13]
Extend to italy with http://it.globalpetrolprices.com/Italy/diesel_prices/

**Comment by derjasper** [comment]
Thanks for the suggestion.
I think this source only provides an average for a given region, but does not provide a list of fuel stations :/
But if there's any other source that is usable please let me know.

**Comment by xXSparkeyy** [comment]
Hey I made a QML Component for my Sailfish project SpritRadar, which provides access to the italian goverments open data. Look at src for all files with the prefix SV. If you need it, you could use it.

**Comment by derjasper** [comment]
Thanks a lot for the tip! Sadly, I cannot find the sources related to Italian data, can you give me a link? Also to the official API description?

**Comment by xXSparkeyy** [comment]
I moved it to a php script (https://github.com/xXSparkeyy/harbour-spritradar/tree/master/php), which could use some optimisation indeed, but works fine for me. If you need the "Api Reference" and source, I will upload a translated version in a few days. I could also recommend taking a look at the spanish script, because it extends the basic data with reversed geocoding to fetch the addresses for the stations.

**Comment by derjasper** [comment]
Okay, thanks for the information ;) I will see how to integrate this into the app when I have finished my exams.

**Comment by floryn90** [comment]
I can help you to implement the dataset for Italy using this project: https://github.com/sabas/carburantiMiSE that that is based on this dataset: https://carburanti.mise.gov.it/OssPrezziSearch/

**Comment by derjasper** [comment]
I would appreciate that! Feel free to fork and create a pull request ;)

Is this project up to date and is there a working live version available? Or do we need an own server?

You may also have a look on how I did implement the service for Spain (see simple-geojson-server and data-fetcher). If there are major re-implementations needed, extending the data-fetcher may be an option.

**Comment by floryn90** [comment]
[UPDATE] I implemented the functions for getting the fuel stations list from the service and in next days i will implement also the station's details (I need to parse an html page because there are no JSON for station's details but only for stations list  :-( ) 
I will also try to translate the app also in italian and romanian (I'm romanian but I'm living in Italy)

**Comment by floryn90** [comment]
I finished the implementation of Italy data set and also I translated to italian. I made a pull request. Please tell me if there are some errors

**Comment by derjasper** [comment]
Thank you, I will have a look in the next days.
Please import the translations at https://translations.launchpad.net/tankenapp ; this makes managing translations and collaboration easier ;) EDIT: I will import your translations when I update the template.

**Comment by derjasper** [comment]
This feature has been released ;) Thanks a lot!
